// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atmxqupqkustgwutjajd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bXhxdXBxa3VzdGd3dXRqYWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjgwOTQsImV4cCI6MjA1ODQwNDA5NH0.g1KNs7I-g9EBhdhNZku2P_BWV0htax0p__MVuRpdaoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);